version: '3'
services:
  mongodb:
    image: mongo:latest
    environment: 
      MONGO_INITDB_ROOT_USERNAME: puppytest
      MONGO_INITDB_ROOT_PASSWORD: puppytestpw
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    # command: mongod --logpath=/dev/null # --quiet
volumes:
  mongodb_data: